version: '3'
services: 
    api:       
        build:
            context: .
            dockerfile:  ./Docker/python/Dockerfile
        volumes: 
            - ./app/:/opt/app
        ports: 
            - 3000:3000
        environment: 
            - FLASK_ENV=development
            - PYTHONUNBUFFERED=1